version: '3.7'

services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: redcontrol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redcontrol
      PGDATA: /var/lib/postgresql/blogs
#    volumes:
#      - /var/lib/postgresql/data
    restart: always

  web:
    build: ./project
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    environment:
      LOG_LEVEL: DEBUG
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DEBUG: 1
      DB_NAME: intranet
      DB_USER: intranet
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  worker:
    build: ./project
    command: celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
