"""empty message

Revision ID: 104a7e445a2d
Revises: 2298ef87a28e
Create Date: 2022-06-12 19:56:54.067200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '104a7e445a2d'
down_revision = '2298ef87a28e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stage_transporter', ['id'])
    op.add_column('transporter', sa.Column('extended_pipline', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_unique_constraint(None, 'transporter', ['id'])
    op.drop_column('transporter', 'extended_sending_survey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transporter', sa.Column('extended_sending_survey', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transporter', type_='unique')
    op.drop_column('transporter', 'extended_pipline')
    op.drop_constraint(None, 'stage_transporter', type_='unique')
    # ### end Alembic commands ###
