"""empty message

Revision ID: 44b1edef91e5
Revises: 6e5d5222432c
Create Date: 2022-06-12 23:16:54.524283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b1edef91e5'
down_revision = '6e5d5222432c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('repositories_token', 'private_token',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'transporter_repositories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transporter_repositories', type_='unique')
    op.alter_column('repositories_token', 'private_token',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('pipline_merge_requests', 'status',
               existing_type=sa.Enum('FAILED', 'DONE', 'PROGRESS', 'FUTURE', name='statusstagetransporter'),
               type_=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'FUTURE'::character varying"))
    # ### end Alembic commands ###
