"""empty message

Revision ID: 55101b4f6bf5
Revises: 74a4f7dd98e4
Create Date: 2022-06-13 15:50:03.452951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55101b4f6bf5'
down_revision = '74a4f7dd98e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('merge_request_id_key', 'merge_request', type_='unique')
    op.drop_column('merge_request', 'id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipline_merge_requests', 'status',
               existing_type=sa.Enum('FAILED', 'DONE', 'PROGRESS', 'FUTURE', name='statusstagetransporter'),
               type_=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'FUTURE'::character varying"))
    op.add_column('merge_request', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint('merge_request_id_key', 'merge_request', ['id'])
    # ### end Alembic commands ###
