"""empty message

Revision ID: 74a4f7dd98e4
Revises: 44b1edef91e5
Create Date: 2022-06-13 13:58:57.323907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a4f7dd98e4'
down_revision = '44b1edef91e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_request', sa.Column('mr_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'merge_request', ['mr_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipline_merge_requests', 'status',
               existing_type=sa.Enum('FAILED', 'DONE', 'PROGRESS', 'FUTURE', name='statusstagetransporter'),
               type_=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'FUTURE'::character varying"))
    op.drop_constraint(None, 'merge_request', type_='unique')
    op.drop_column('merge_request', 'mr_id')
    # ### end Alembic commands ###
