"""empty message

Revision ID: 8e03f0ce3db4
Revises: 55101b4f6bf5
Create Date: 2022-06-13 15:51:00.567438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e03f0ce3db4'
down_revision = '55101b4f6bf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_request', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('merge_request_mr_id_key', 'merge_request', type_='unique')
    op.create_unique_constraint(None, 'merge_request', ['id'])
    op.drop_column('merge_request', 'mr_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipline_merge_requests', 'status',
               existing_type=sa.Enum('FAILED', 'DONE', 'PROGRESS', 'FUTURE', name='statusstagetransporter'),
               type_=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'FUTURE'::character varying"))
    op.add_column('merge_request', sa.Column('mr_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'merge_request', type_='unique')
    op.create_unique_constraint('merge_request_mr_id_key', 'merge_request', ['mr_id'])
    op.drop_column('merge_request', 'id')
    # ### end Alembic commands ###
