"""empty message

Revision ID: d899771edb71
Revises: 8e03f0ce3db4
Create Date: 2022-06-13 19:18:52.184259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd899771edb71'
down_revision = '8e03f0ce3db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('created', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('container_pipline_merge_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipline_mr_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipline_mr_id'], ['pipline_merge_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipline_merge_requests', 'status',
               existing_type=sa.Enum('FAILED', 'DONE', 'PROGRESS', 'FUTURE', name='statusstagetransporter'),
               type_=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'FUTURE'::character varying"))
    op.drop_table('container_pipline_merge_requests')
    op.drop_table('container')
    # ### end Alembic commands ###
